//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eyedia.IDPE.Clients
{
    using System.Runtime.Serialization;
    using Eyedia.IDPE.Services;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Eyedia.IDPE.Clients.IIdpeEnvironmentService")]
    public interface IIdpeEnvironmentService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/Ping", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/PingResponse")]
        string Ping(EnvironmentServicePacket packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/Ping", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/PingResponse")]
        System.Threading.Tasks.Task<string> PingAsync(EnvironmentServicePacket packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/GetNumberOfInstances", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/GetNumberOfInstancesResponse")]
        int GetNumberOfInstances(EnvironmentServicePacket packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/GetNumberOfInstances", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/GetNumberOfInstancesResponse")]
        System.Threading.Tasks.Task<int> GetNumberOfInstancesAsync(EnvironmentServicePacket packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/ExecuteCommand", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/ExecuteCommandResponse")]
        string ExecuteCommand(EnvironmentServicePacket packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/ExecuteCommand", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/ExecuteCommandResponse")]
        System.Threading.Tasks.Task<string> ExecuteCommandAsync(EnvironmentServicePacket packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/Deploy", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/DeployResponse")]
        string Deploy(EnvironmentServicePacket packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/Deploy", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/DeployResponse")]
        System.Threading.Tasks.Task<string> DeployAsync(EnvironmentServicePacket packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/DeploySdf", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/DeploySdfResponse")]
        string DeploySdf(EnvironmentServicePacket packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/DeploySdf", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/DeploySdfResponse")]
        System.Threading.Tasks.Task<string> DeploySdfAsync(EnvironmentServicePacket packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/DeployArtifacts", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/DeployArtifactsResponse")]
        string DeployArtifacts(EnvironmentServicePacket packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/DeployArtifacts", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/DeployArtifactsResponse")]
        System.Threading.Tasks.Task<string> DeployArtifactsAsync(EnvironmentServicePacket packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/GetLastDeploymentLog", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/GetLastDeploymentLogResponse")]
        Eyedia.IDPE.Common.FileTransferPacket GetLastDeploymentLog();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/GetLastDeploymentLog", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/GetLastDeploymentLogResponse")]
        System.Threading.Tasks.Task<Eyedia.IDPE.Common.FileTransferPacket> GetLastDeploymentLogAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/ProcessFile", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/ProcessFileResponse")]
        string ProcessFile(EnvironmentServicePacket packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/ProcessFile", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/ProcessFileResponse")]
        System.Threading.Tasks.Task<string> ProcessFileAsync(EnvironmentServicePacket packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/GetDataSources", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/GetDataSourcesResponse")]
        Eyedia.IDPE.DataManager.IdpeDataSource[] GetDataSources(EnvironmentServicePacket packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/GetDataSources", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/GetDataSourcesResponse")]
        System.Threading.Tasks.Task<Eyedia.IDPE.DataManager.IdpeDataSource[]> GetDataSourcesAsync(EnvironmentServicePacket packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/GetConfigFile", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/GetConfigFileResponse")]
        Eyedia.IDPE.Common.FileTransferPacket GetConfigFile(EnvironmentServicePacket packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/GetConfigFile", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/GetConfigFileResponse")]
        System.Threading.Tasks.Task<Eyedia.IDPE.Common.FileTransferPacket> GetConfigFileAsync(EnvironmentServicePacket packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/SetConfigFile", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/SetConfigFileResponse")]
        string SetConfigFile(EnvironmentServicePacket packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/SetConfigFile", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/SetConfigFileResponse")]
        System.Threading.Tasks.Task<string> SetConfigFileAsync(EnvironmentServicePacket packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/SetServiceLogonUser", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/SetServiceLogonUserResponse")]
        string SetServiceLogonUser(EnvironmentServicePacket packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdpeEnvironmentService/SetServiceLogonUser", ReplyAction="http://tempuri.org/IIdpeEnvironmentService/SetServiceLogonUserResponse")]
        System.Threading.Tasks.Task<string> SetServiceLogonUserAsync(EnvironmentServicePacket packet);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIdpeEnvironmentServiceChannel : Eyedia.IDPE.Clients.IIdpeEnvironmentService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IdpeEnvironmentServiceClient : System.ServiceModel.ClientBase<Eyedia.IDPE.Clients.IIdpeEnvironmentService>, Eyedia.IDPE.Clients.IIdpeEnvironmentService
    {
        
        public IdpeEnvironmentServiceClient()
        {
        }
        
        public IdpeEnvironmentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public IdpeEnvironmentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public IdpeEnvironmentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public IdpeEnvironmentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string Ping(EnvironmentServicePacket packet)
        {
            return base.Channel.Ping(packet);
        }
        
        public System.Threading.Tasks.Task<string> PingAsync(EnvironmentServicePacket packet)
        {
            return base.Channel.PingAsync(packet);
        }
        
        public int GetNumberOfInstances(EnvironmentServicePacket packet)
        {
            return base.Channel.GetNumberOfInstances(packet);
        }
        
        public System.Threading.Tasks.Task<int> GetNumberOfInstancesAsync(EnvironmentServicePacket packet)
        {
            return base.Channel.GetNumberOfInstancesAsync(packet);
        }
        
        public string ExecuteCommand(EnvironmentServicePacket packet)
        {
            return base.Channel.ExecuteCommand(packet);
        }
        
        public System.Threading.Tasks.Task<string> ExecuteCommandAsync(EnvironmentServicePacket packet)
        {
            return base.Channel.ExecuteCommandAsync(packet);
        }
        
        public string Deploy(EnvironmentServicePacket packet)
        {
            return base.Channel.Deploy(packet);
        }
        
        public System.Threading.Tasks.Task<string> DeployAsync(EnvironmentServicePacket packet)
        {
            return base.Channel.DeployAsync(packet);
        }
        
        public string DeploySdf(EnvironmentServicePacket packet)
        {
            return base.Channel.DeploySdf(packet);
        }
        
        public System.Threading.Tasks.Task<string> DeploySdfAsync(EnvironmentServicePacket packet)
        {
            return base.Channel.DeploySdfAsync(packet);
        }
        
        public string DeployArtifacts(EnvironmentServicePacket packet)
        {
            return base.Channel.DeployArtifacts(packet);
        }
        
        public System.Threading.Tasks.Task<string> DeployArtifactsAsync(EnvironmentServicePacket packet)
        {
            return base.Channel.DeployArtifactsAsync(packet);
        }
        
        public Eyedia.IDPE.Common.FileTransferPacket GetLastDeploymentLog()
        {
            return base.Channel.GetLastDeploymentLog();
        }
        
        public System.Threading.Tasks.Task<Eyedia.IDPE.Common.FileTransferPacket> GetLastDeploymentLogAsync()
        {
            return base.Channel.GetLastDeploymentLogAsync();
        }
        
        public string ProcessFile(EnvironmentServicePacket packet)
        {
            return base.Channel.ProcessFile(packet);
        }
        
        public System.Threading.Tasks.Task<string> ProcessFileAsync(EnvironmentServicePacket packet)
        {
            return base.Channel.ProcessFileAsync(packet);
        }
        
        public Eyedia.IDPE.DataManager.IdpeDataSource[] GetDataSources(EnvironmentServicePacket packet)
        {
            return base.Channel.GetDataSources(packet);
        }
        
        public System.Threading.Tasks.Task<Eyedia.IDPE.DataManager.IdpeDataSource[]> GetDataSourcesAsync(EnvironmentServicePacket packet)
        {
            return base.Channel.GetDataSourcesAsync(packet);
        }
        
        public Eyedia.IDPE.Common.FileTransferPacket GetConfigFile(EnvironmentServicePacket packet)
        {
            return base.Channel.GetConfigFile(packet);
        }
        
        public System.Threading.Tasks.Task<Eyedia.IDPE.Common.FileTransferPacket> GetConfigFileAsync(EnvironmentServicePacket packet)
        {
            return base.Channel.GetConfigFileAsync(packet);
        }
        
        public string SetConfigFile(EnvironmentServicePacket packet)
        {
            return base.Channel.SetConfigFile(packet);
        }
        
        public System.Threading.Tasks.Task<string> SetConfigFileAsync(EnvironmentServicePacket packet)
        {
            return base.Channel.SetConfigFileAsync(packet);
        }
        
        public string SetServiceLogonUser(EnvironmentServicePacket packet)
        {
            return base.Channel.SetServiceLogonUser(packet);
        }
        
        public System.Threading.Tasks.Task<string> SetServiceLogonUserAsync(EnvironmentServicePacket packet)
        {
            return base.Channel.SetServiceLogonUserAsync(packet);
        }
    }
}
