<?xml version="1.0" encoding="utf-8"?><Database Name="idpe" EntityNamespace="Eyedia.IDPE.DataManager" Class="RepositoryDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LPT-03084856325\SQLEXPRESS;Initial Catalog=idpe;Integrated Security=True" SettingsObjectName="Eyedia.IDPE.DataManager.Properties.Settings" SettingsPropertyName="surface" Provider="System.Data.SqlClient" />
  <Table Name="dbo.IdpeAttribute" Member="IdpeAttributes">
    <Type Name="IdpeAttribute">
      <Column Name="AttributeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Minimum" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Maximum" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Formula" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="IsAcceptable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Position" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AttributePrintValueType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AttributePrintValueCustom" Type="System.String" DbType="VarChar(4000)" CanBeNull="true" />
      <Column Name="CreatedTS" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedTS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="IdpeAttribute_IdpeAttributeDataSource" Member="IdpeAttributeDataSources" ThisKey="AttributeId" OtherKey="AttributeId" Type="IdpeAttributeDataSource" />
    </Type>
  </Table>
  <Table Name="dbo.IdpeAttributeDataSource" Member="IdpeAttributeDataSources">
    <Type Name="IdpeAttributeDataSource">
      <Column Name="AttributeDataSourceId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DataSourceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AttributeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsAcceptable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AttributePrintValueType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AttributePrintValueCustom" Type="System.String" DbType="VarChar(4000)" CanBeNull="true" />
      <Column Name="CreatedTS" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedTS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="IdpeAttribute_IdpeAttributeDataSource" Member="IdpeAttribute" ThisKey="AttributeId" OtherKey="AttributeId" Type="IdpeAttribute" IsForeignKey="true" />
      <Association Name="IdpeDataSource_IdpeAttributeDataSource" Member="IdpeDataSource" ThisKey="DataSourceId" OtherKey="Id" Type="IdpeDataSource" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.IdpeDataSource" Member="IdpeDataSources">
    <Type Name="IdpeDataSource">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="IsSystem" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DataFeederType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DataFormatType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Delimiter" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="SystemDataSourceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DataContainerValidatorType" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="OutputType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OutputWriterTypeFullName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PlugInsType" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ProcessingBy" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PusherType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PusherTypeFullName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedTS" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedTS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="IdpeDataSource_IdpeAttributeDataSource" Member="IdpeAttributeDataSources" ThisKey="Id" OtherKey="DataSourceId" Type="IdpeAttributeDataSource" />
      <Association Name="IdpeDataSource_IdpeDataSource" Member="IdpeDataSources" ThisKey="Id" OtherKey="SystemDataSourceId" Type="IdpeDataSource" />
      <Association Name="IdpeDataSource_IdpeKeyDataSource" Member="IdpeKeyDataSources" ThisKey="Id" OtherKey="DataSourceId" Type="IdpeKeyDataSource" />
      <Association Name="IdpeDataSource_IdpeLog" Member="IdpeLogs" ThisKey="Id" OtherKey="DataSourceId" Type="IdpeLog" />
      <Association Name="IdpeDataSource_IdpePersistentVariable" Member="IdpePersistentVariables" ThisKey="Id" OtherKey="DataSourceId" Type="IdpePersistentVariable" />
      <Association Name="IdpeDataSource_IdpeRuleDataSource" Member="IdpeRuleDataSources" ThisKey="Id" OtherKey="DataSourceId" Type="IdpeRuleDataSource" />
      <Association Name="IdpeDataSource_IdpeDataSource" Member="IdpeDataSource1" ThisKey="SystemDataSourceId" OtherKey="Id" Type="IdpeDataSource" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.IdpeKey" Member="IdpeKeys">
    <Type Name="IdpeKey">
      <Column Name="KeyId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(4000)" CanBeNull="true" />
      <Column Name="ValueBinary" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDeployable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DataSourceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NextKeyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedTS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedTS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="IdpeKey_IdpeKey" Member="IdpeKeys" ThisKey="KeyId" OtherKey="NextKeyId" Type="IdpeKey" />
      <Association Name="IdpeKey_IdpeKeyDataSource" Member="IdpeKeyDataSources" ThisKey="KeyId" OtherKey="KeyId" Type="IdpeKeyDataSource" />
      <Association Name="IdpeKey_IdpeKey" Member="IdpeKey1" ThisKey="NextKeyId" OtherKey="KeyId" Type="IdpeKey" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.IdpeKeyDataSource" Member="IdpeKeyDataSources">
    <Type Name="IdpeKeyDataSource">
      <Column Name="KeyDataSourceId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KeyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataSourceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDeployable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedTS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedTS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="IdpeDataSource_IdpeKeyDataSource" Member="IdpeDataSource" ThisKey="DataSourceId" OtherKey="Id" Type="IdpeDataSource" IsForeignKey="true" />
      <Association Name="IdpeKey_IdpeKeyDataSource" Member="IdpeKey" ThisKey="KeyId" OtherKey="KeyId" Type="IdpeKey" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.IdpeLog" Member="IdpeLogs">
    <Type Name="IdpeLog">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SubFileName" Type="System.String" DbType="VarChar(260)" CanBeNull="true" />
      <Column Name="DataSourceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataSourceName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TotalRecords" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalValidRecords" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Started" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Finished" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Environment" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedTS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedTS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="IdpeDataSource_IdpeLog" Member="IdpeDataSource" ThisKey="DataSourceId" OtherKey="Id" Type="IdpeDataSource" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.IdpePersistentVariable" Member="IdpePersistentVariables">
    <Type Name="IdpePersistentVariable">
      <Column Name="DataSourceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedTS" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedTS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="IdpeDataSource_IdpePersistentVariable" Member="IdpeDataSource" ThisKey="DataSourceId" OtherKey="Id" Type="IdpeDataSource" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.IdpeRule" Member="IdpeRules">
    <Type Name="IdpeRule">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Xaml" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Priority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RuleSetType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedTS" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedTS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="IdpeRule_IdpeRuleDataSource" Member="IdpeRuleDataSources" ThisKey="Id" OtherKey="RuleId" Type="IdpeRuleDataSource" />
    </Type>
  </Table>
  <Table Name="dbo.IdpeRuleDataSource" Member="IdpeRuleDataSources">
    <Type Name="IdpeRuleDataSource">
      <Column Name="RuleDataSourceId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RuleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataSourceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RuleSetType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedTS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ModifiedTS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="IdpeDataSource_IdpeRuleDataSource" Member="IdpeDataSource" ThisKey="DataSourceId" OtherKey="Id" Type="IdpeDataSource" IsForeignKey="true" />
      <Association Name="IdpeRule_IdpeRuleDataSource" Member="IdpeRule" ThisKey="RuleId" OtherKey="Id" Type="IdpeRule" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.IdpeVersion" Member="IdpeVersions">
    <Type Name="IdpeVersion">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Version" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReferenceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="CreatedTS" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedTS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>