//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eyedia.IDPE.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eyedia.IDPE.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define ....
        /// </summary>
        internal static string DefineButtonContent {
            get {
                return ResourceManager.GetString("DefineButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Arguments.
        /// </summary>
        internal static string DynamicArgumentDialogTitle {
            get {
                return ResourceManager.GetString("DynamicArgumentDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string ElipsesButtonContent {
            get {
                return ResourceManager.GetString("ElipsesButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment variable &quot;{0}&quot; not defined.
        /// </summary>
        internal static string EnvironmentVariableNotDefinedErrorText {
            get {
                return ResourceManager.GetString("EnvironmentVariableNotDefinedErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load workflow, {0}.
        /// </summary>
        internal static string FailedToLoadWorkflowValidationErrorText {
            get {
                return ResourceManager.GetString("FailedToLoadWorkflowValidationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must have an argument type of {1}.
        /// </summary>
        internal static string InvalidIArgumentTypeValidationErrorText {
            get {
                return ResourceManager.GetString("InvalidIArgumentTypeValidationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not an argument of loaded dynamic activity.
        /// </summary>
        internal static string InvalidIArgumentValidationErrorText {
            get {
                return ResourceManager.GetString("InvalidIArgumentValidationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must have an In argument direction.
        /// </summary>
        internal static string InvalidInArgumentDirectionValidationErrorText {
            get {
                return ResourceManager.GetString("InvalidInArgumentDirectionValidationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must have an InOut argument direction.
        /// </summary>
        internal static string InvalidInOutArgumentDirectionValidationErrorText {
            get {
                return ResourceManager.GetString("InvalidInOutArgumentDirectionValidationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must have an Out argument direction.
        /// </summary>
        internal static string InvalidOutArgumentDirectionValidationErrorText {
            get {
                return ResourceManager.GetString("InvalidOutArgumentDirectionValidationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify valid workflow.
        /// </summary>
        internal static string SpecifyValidWorkflowValidationErrorText {
            get {
                return ResourceManager.GetString("SpecifyValidWorkflowValidationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string UndefinedPathErrorText {
            get {
                return ResourceManager.GetString("UndefinedPathErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Arguments.
        /// </summary>
        internal static string WorkflowArgumentsTextBlockText {
            get {
                return ResourceManager.GetString("WorkflowArgumentsTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow File.
        /// </summary>
        internal static string WorkflowFileTextBlockText {
            get {
                return ResourceManager.GetString("WorkflowFileTextBlockText", resourceCulture);
            }
        }
    }
}
