//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eyedia.IDPE.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SreMessageCodeDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SreMessageCodeDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eyedia.IDPE.Common.SreMessageCodeDescriptions", typeof(SreMessageCodeDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute assign failed. Please check server log for more details.
        /// </summary>
        internal static string SRE_ATTRIBUTE_ASSIGN_FAILED {
            get {
                return ResourceManager.GetString("SRE_ATTRIBUTE_ASSIGN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Expecting a &apos;{1}&apos; type data and it failed with value &apos;{2}&apos;.
        /// </summary>
        internal static string SRE_BIGINT_TYPE_DATA_VALIDATION_FAILED {
            get {
                return ResourceManager.GetString("SRE_BIGINT_TYPE_DATA_VALIDATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Expecting a &apos;{1}&apos; type data and it failed with value &apos;{2}&apos;.
        /// </summary>
        internal static string SRE_BIT_TYPE_DATA_VALIDATION_FAILED {
            get {
                return ResourceManager.GetString("SRE_BIT_TYPE_DATA_VALIDATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;{1}&apos; is invalid..
        /// </summary>
        internal static string SRE_CODESET_TYPE_DATA_VALIDATION_FAILED {
            get {
                return ResourceManager.GetString("SRE_CODESET_TYPE_DATA_VALIDATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Conainter validation is failed&quot;.
        /// </summary>
        internal static string SRE_CONTAINER_VALIDATION_FAILED {
            get {
                return ResourceManager.GetString("SRE_CONTAINER_VALIDATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Container validation is failed for the row &apos;{0}&apos;. Error is &apos;{1}&apos;&quot;.
        /// </summary>
        internal static string SRE_CONTAINER_VALIDATION_FAILED_ROW {
            get {
                return ResourceManager.GetString("SRE_CONTAINER_VALIDATION_FAILED_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Expecting a &apos;{1}&apos; type data and it failed with value &apos;{2}&apos;.
        /// </summary>
        internal static string SRE_DATE_TYPE_DATA_VALIDATION_FAILED {
            get {
                return ResourceManager.GetString("SRE_DATE_TYPE_DATA_VALIDATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Expecting a &apos;{1}&apos; type data and it failed with value &apos;{2}&apos;.
        /// </summary>
        internal static string SRE_DECIMAL_TYPE_DATA_VALIDATION_FAILED {
            get {
                return ResourceManager.GetString("SRE_DECIMAL_TYPE_DATA_VALIDATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed!.
        /// </summary>
        internal static string SRE_FAILED {
            get {
                return ResourceManager.GetString("SRE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SRE_FAILED_BLANK {
            get {
                return ResourceManager.GetString("SRE_FAILED_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error processing the file.
        /// </summary>
        internal static string SRE_FILE_GENERIC {
            get {
                return ResourceManager.GetString("SRE_FILE_GENERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has been configured to support only &apos;{1}&apos; type(s) of file. The file &apos;{2}&apos; was ignored..
        /// </summary>
        internal static string SRE_FILE_TYPE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("SRE_FILE_TYPE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Invalid generation formula &apos;{1}&apos; in GENERATED type column {2}..
        /// </summary>
        internal static string SRE_GENERATED_TYPE_DATA_VALIDATION_FAILED {
            get {
                return ResourceManager.GetString("SRE_GENERATED_TYPE_DATA_VALIDATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Expecting a &apos;{1}&apos; type data and it failed with value &apos;{2}&apos;.
        /// </summary>
        internal static string SRE_INT_TYPE_DATA_VALIDATION_FAILED {
            get {
                return ResourceManager.GetString("SRE_INT_TYPE_DATA_VALIDATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;{1}&apos; already exists, existing value not acceptable in {2}. If you sure about correctness, please check other dependent column(s). Existing value might be allowed in case of &apos;Modifications&apos;, &apos;Cancellations&apos;..
        /// </summary>
        internal static string SRE_NOT_REFERENCED_TYPE_DATA_RESULT_FOUND {
            get {
                return ResourceManager.GetString("SRE_NOT_REFERENCED_TYPE_DATA_RESULT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SRE_NOT_REFERENCED_TYPE_DATA_RESULT_NOT_FOUND {
            get {
                return ResourceManager.GetString("SRE_NOT_REFERENCED_TYPE_DATA_RESULT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin method execution failed. Error Id = {0}.
        /// </summary>
        internal static string SRE_PLUGIN_METHOD_EXECUTION_FAILED {
            get {
                return ResourceManager.GetString("SRE_PLUGIN_METHOD_EXECUTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin method not defined or its failed to execute.
        /// </summary>
        internal static string SRE_PLUGIN_METHOD_EXECUTION_FAILED_METHOD_NOT_DEFINED {
            get {
                return ResourceManager.GetString("SRE_PLUGIN_METHOD_EXECUTION_FAILED_METHOD_NOT_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Invalid value &apos;{1}&apos;. &apos;{2}&apos; can not be empty or blank..
        /// </summary>
        internal static string SRE_REFERENCED_TYPE_DATA_CAN_NOT_BE_NULL {
            get {
                return ResourceManager.GetString("SRE_REFERENCED_TYPE_DATA_CAN_NOT_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SRE_REFERENCED_TYPE_DATA_RESULT_FOUND {
            get {
                return ResourceManager.GetString("SRE_REFERENCED_TYPE_DATA_RESULT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Invalid value &apos;{1}&apos;. Referenced type &apos;{2}&apos; not found..
        /// </summary>
        internal static string SRE_REFERENCED_TYPE_DATA_RESULT_NOT_FOUND {
            get {
                return ResourceManager.GetString("SRE_REFERENCED_TYPE_DATA_RESULT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Expecting a &apos;{1}&apos; type data and it failed with value &apos;{2}&apos;.
        /// </summary>
        internal static string SRE_STRING_TYPE_DATA_VALIDATION_FAILED {
            get {
                return ResourceManager.GetString("SRE_STRING_TYPE_DATA_VALIDATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SRE_SUCCESS {
            get {
                return ResourceManager.GetString("SRE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A critical error occurred. Please contact technical support..
        /// </summary>
        internal static string SRE_TYPE_DATA_VALIDATION_FAILED_GENERIC {
            get {
                return ResourceManager.GetString("SRE_TYPE_DATA_VALIDATION_FAILED_GENERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1} should be less than {2}.
        /// </summary>
        internal static string SRE_TYPE_DATA_VALIDATION_FAILED_MAXIMUM {
            get {
                return ResourceManager.GetString("SRE_TYPE_DATA_VALIDATION_FAILED_MAXIMUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;{1:d}&apos; has to be less than current server date &apos;{2:d}&apos;.
        /// </summary>
        internal static string SRE_TYPE_DATA_VALIDATION_FAILED_MAXIMUM_DATE_SERVER {
            get {
                return ResourceManager.GetString("SRE_TYPE_DATA_VALIDATION_FAILED_MAXIMUM_DATE_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;{1}&apos; has to be less than current server date &amp; time &apos;{2}&apos;.
        /// </summary>
        internal static string SRE_TYPE_DATA_VALIDATION_FAILED_MAXIMUM_DATETIME_SERVER {
            get {
                return ResourceManager.GetString("SRE_TYPE_DATA_VALIDATION_FAILED_MAXIMUM_DATETIME_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Maximum length allowed in &apos;{1}&apos; is {2}.
        /// </summary>
        internal static string SRE_TYPE_DATA_VALIDATION_FAILED_MAXIMUM_STRING {
            get {
                return ResourceManager.GetString("SRE_TYPE_DATA_VALIDATION_FAILED_MAXIMUM_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1} should be greater than {2}.
        /// </summary>
        internal static string SRE_TYPE_DATA_VALIDATION_FAILED_MINIMUM {
            get {
                return ResourceManager.GetString("SRE_TYPE_DATA_VALIDATION_FAILED_MINIMUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;{1:d}&apos; has to be greater than current server date &apos;{2:d}&apos;.
        /// </summary>
        internal static string SRE_TYPE_DATA_VALIDATION_FAILED_MINIMUM_DATE_SERVER {
            get {
                return ResourceManager.GetString("SRE_TYPE_DATA_VALIDATION_FAILED_MINIMUM_DATE_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;{1}&apos; has to be greater than current server date &amp; time &apos;{2}&apos;.
        /// </summary>
        internal static string SRE_TYPE_DATA_VALIDATION_FAILED_MINIMUM_DATETIME_SERVER {
            get {
                return ResourceManager.GetString("SRE_TYPE_DATA_VALIDATION_FAILED_MINIMUM_DATETIME_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;{1}&apos; has to be greater than or equal to &apos;{2}&apos; and less than or equal to &apos;{3}&apos;.
        /// </summary>
        internal static string SRE_TYPE_DATA_VALIDATION_FAILED_MINIMUM_MAXIMUM_DATE {
            get {
                return ResourceManager.GetString("SRE_TYPE_DATA_VALIDATION_FAILED_MINIMUM_MAXIMUM_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Length of &apos;{1}&apos; should be at least {2}.
        /// </summary>
        internal static string SRE_TYPE_DATA_VALIDATION_FAILED_MINIMUM_STRING {
            get {
                return ResourceManager.GetString("SRE_TYPE_DATA_VALIDATION_FAILED_MINIMUM_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A critical error occurred. Value can not be updated at this time, please contact support..
        /// </summary>
        internal static string SRE_TYPE_DATA_VALIDATION_FAILED_VALUE_UPDATION_NOT_PERMITTED {
            get {
                return ResourceManager.GetString("SRE_TYPE_DATA_VALIDATION_FAILED_VALUE_UPDATION_NOT_PERMITTED", resourceCulture);
            }
        }
    }
}
