#region Copyright Notice
/* Copyright (c) 2017, Deb'jyoti Das - debjyoti@debjyoti.com
 All rights reserved.
 Redistribution and use in source and binary forms, with or without
 modification, are not permitted.Neither the name of the 
 'Deb'jyoti Das' nor the names of its contributors may be used 
 to endorse or promote products derived from this software without 
 specific prior written permission.
 THIS SOFTWARE IS PROVIDED BY Deb'jyoti Das 'AS IS' AND ANY
 EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL Debjyoti OR Deb'jyoti OR Debojyoti Das OR Eyedia BE LIABLE FOR ANY
 DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#region Developer Information
/*
Author  - Deb'jyoti Das
Created - 3/19/2013 11:14:16 AM
Description  - 
Modified By - 
Description  - 
*/
#endregion Developer Information

#endregion Copyright Notice



using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Eyedia.IDPE.Common
{
    public enum SreMessageCodes
    {
        //SRE Engine
        SRE_SUCCESS = 100,
        SRE_FAILED = 101,
        SRE_UNKNOWN_ERROR = 103,
        SRE_FAILED_BLANK = 104,


        //SREType (generic)
        SRE_TYPE_DATA_VALIDATION_FAILED_GENERIC = 200,
        SRE_TYPE_DATA_VALIDATION_FAILED_MINIMUM = 201,
        SRE_TYPE_DATA_VALIDATION_FAILED_MAXIMUM = 202,
        SRE_TYPE_DATA_VALIDATION_FAILED_MINIMUM_STRING = 203,
        SRE_TYPE_DATA_VALIDATION_FAILED_MAXIMUM_STRING = 204,
        SRE_TYPE_DATA_VALIDATION_FAILED_MINIMUM_DATETIME_SERVER = 205,
        SRE_TYPE_DATA_VALIDATION_FAILED_MAXIMUM_DATETIME_SERVER = 206,
        SRE_TYPE_DATA_VALIDATION_FAILED_MINIMUM_DATE_SERVER = 207,
        SRE_TYPE_DATA_VALIDATION_FAILED_MAXIMUM_DATE_SERVER = 208,
        SRE_TYPE_DATA_VALIDATION_FAILED_MINIMUM_MAXIMUM_DATE = 209,
        SRE_TYPE_DATA_VALIDATION_FAILED_VALUE_UPDATION_NOT_PERMITTED = 210,        
        

        //SREType specific
        SRE_INT_TYPE_DATA_VALIDATION_FAILED = 301,
        SRE_BIGINT_TYPE_DATA_VALIDATION_FAILED = 302,
        SRE_DECIMAL_TYPE_DATA_VALIDATION_FAILED = 303,
        SRE_BIT_TYPE_DATA_VALIDATION_FAILED = 304,
        SRE_STRING_TYPE_DATA_VALIDATION_FAILED = 305,
        SRE_REFERENCED_TYPE_DATA_RESULT_FOUND = 306,
        SRE_REFERENCED_TYPE_DATA_RESULT_NOT_FOUND = 307,
        SRE_REFERENCED_TYPE_DATA_CAN_NOT_BE_NULL = 308,
        SRE_NOT_REFERENCED_TYPE_DATA_RESULT_FOUND = 309,
        SRE_NOT_REFERENCED_TYPE_DATA_RESULT_NOT_FOUND = 310,
        SRE_DATE_TYPE_DATA_VALIDATION_FAILED = 311,
        SRE_GENERATED_TYPE_DATA_VALIDATION_FAILED = 312,
        SRE_CODESET_TYPE_DATA_VALIDATION_FAILED = 313,

        //Plugin specific
        SRE_PLUGIN_METHOD_EXECUTION_FAILED = 501,
        SRE_PLUGIN_METHOD_EXECUTION_FAILED_METHOD_NOT_DEFINED = 502,

        //attribute
        SRE_ATTRIBUTE_ASSIGN_FAILED = 601,

        //container
        SRE_CONTAINER_VALIDATION_FAILED = 701,
        SRE_CONTAINER_VALIDATION_FAILED_ROW = 702,

        //file types
        SRE_FILE_GENERIC = 801,
        SRE_FILE_TYPE_NOT_SUPPORTED = 802
    }
}




