//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eyedia.IDPE.Interface.RuleEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eyedia.IDPE.Interface.RuleEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        internal static string CollectionCategoryToToolbox {
            get {
                return ResourceManager.GetString("CollectionCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Flows.
        /// </summary>
        internal static string ControlFlowCategoryToToolbox {
            get {
                return ResourceManager.GetString("ControlFlowCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Handling.
        /// </summary>
        internal static string ErrorHandlingCategoryToToolbox {
            get {
                return ResourceManager.GetString("ErrorHandlingCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorValidationItem {
            get {
                return ResourceManager.GetString("ErrorValidationItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flowchart.
        /// </summary>
        internal static string FlowchartCategoryToToolbox {
            get {
                return ResourceManager.GetString("FlowchartCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging.
        /// </summary>
        internal static string MessagingCategoryToToolbox {
            get {
                return ResourceManager.GetString("MessagingCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primitives.
        /// </summary>
        internal static string PrimitivesCategoryToToolbox {
            get {
                return ResourceManager.GetString("PrimitivesCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime.
        /// </summary>
        internal static string RuntimeCategoryToToolbox {
            get {
                return ResourceManager.GetString("RuntimeCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDPE.Services.
        /// </summary>
        internal static string SymplusServicesCategoryToToolbox {
            get {
                return ResourceManager.GetString("SymplusServicesCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        internal static string TransactionCategoryToToolbox {
            get {
                return ResourceManager.GetString("TransactionCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningValidationItem {
            get {
                return ResourceManager.GetString("WarningValidationItem", resourceCulture);
            }
        }
    }
}
